### ISSUE TITLE
Q. How to remove keys on merge?

### ISSUE THREAD

**Issue by cunningr** [adobe/himl#158]
### Expected Behaviour

If I am setting a key/object in my top level `globals.yaml` at a specific lower level, I want to be able to remove that key (e.g. not just set the `value: null` but actually `del`).  For example:

`global.yaml`
```
modules_to_deploy:
  module1: <config-mod1>
  module2: <config-mod1>
  module3: <config-mod1>
```

then in my `special_dr_site.yaml`:

```
modules_to_deploy:
  module1: <config-mod1>
  module2: #remove
  module3: <config-mod1>
``` 

After merging, for my `special_dr_site`, I want the resulting yaml to be:

```
modules_to_deploy:
  module1: <config-mod1>
  module3: <config-mod1>
``` 

### Actual Behaviour

Not sure if/how this can be achieved?

### Reproduce Scenario (including but not limited to)

simply try the simple example above.

#### Steps to Reproduce

see above example

#### Platform and Version

Any
