### ISSUE TITLE
Select among multiple .yaml files

### ISSUE THREAD

**Issue by Revaapriyan** [adobe/himl#41]
Consider a `config` folder structure as below
```
configs
├─ prod
│   |─ zone1.yaml
│   └─ zone2.yaml
└─ default.yaml
```
default.yaml contains
```
path:
    parent: data
    result_path: "{{path.parent}}/{{zone.name}}/{{path.exp_name}}"
```
prod/zone1.yaml
```
zone:
   name: zone_A
path:
    exp_name : exp1
```
prod/zone2.yaml
```
zone:
   name: zone_B
path:
    exp_name : test
run:
    description: "testing himl"
```

code snippet:
```
from himl import ConfigProcessor
config = ConfigProcessor().process(path='configs/prod', print_data=True)
```
### Expected Behaviour
`default.yaml` has default configurations that will be overridden by any of the selected `zone` configurations. An error to ask to chose between `zone1.yaml` and `zone2.yaml` files.

### Actual Behaviour
the code resulted in merging the files by itself and provides the following as output.
```
path:
  exp_name: test
  parent: data
  result_path: data/zone_B/test
zone:
  name: zone_B
run:
  description: testing himl
```
#### Platform and Version
Platform: Ubuntu 20.04 LTS
himl version: v0.7.1
