### ISSUE TITLE
[Feature Request] himl cli - deep filter

### ISSUE THREAD

**Issue by tiger-revaapriyan** [adobe/himl#42]
Consider the following `.yaml` file.

examples/simple/default.yaml
```
deep:
  key1: v1
  key2: v2
deep_list:
- item1
- item2
```
## Request 
A feature to filter deep keys like, `deep.key1`, `deep.key2`. Currently, the cli supports only top-level keys to filter. (ie, `deep` and ` deep_list` in the example)
